[[plugins]]
repo = "Shougo/dein.vim"

[[plugins]]
repo = "altercation/vim-colors-solarized"

[[plugins]]
repo = "ConradIrwin/vim-bracketed-paste"
 
[[plugins]]
repo = "itchyny/lightline.vim"
hook_add = """
	set laststatus=2
	let g:lightline = {'colorscheme': 'solarized'}
"""
