[[plugins]]
repo = "Shougo/unite.vim"

[[plugins]]
repo = "Shougo/neomru.vim"
on_source = ["unite.vim"]

[[plugins]]
repo = "Shougo/neocomplete.vim"
hook_add = """
    let g:neocomplete#enable_at_startup = 1
"""
on_i = 1

[[plugins]]
repo = "davidhalter/jedi-vim"
on_ft = ["python"]
hook_add = """
    let g:jedi#popup_select_first = 0
    let g:jedi#popup_on_dot = 0
"""

[[plugins]]
repo = "lambdalisue/vim-pyenv"
depends = ["davidhalter/jedi-vim"]
